apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ka5fl7cf5-nodejs
  janus-idp.io/tekton: ka5fl7cf5-nodejs
  backstage.io/kubernetes-id: ka5fl7cf5-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ka5fl7cf5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
