apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ka5fl7cf5-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ka5fl7cf5-nodejs 
  name: ka5fl7cf5-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ka5fl7cf5-nodejs 
