apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ka5fl7cf5-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:27670a23a8b94adc27a44b4f4fb4299a8b897700@sha256:1f2725e39caecf0f620f0e84b9b4e0382c4a5ead912f5e31a0ee492f8f73dacd
          name: container-image
